version: '3.5'

networks: 
  webnet:
    driver: overlay
    attachable: true

services:
  web:
    image: "teberl/phx_client:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 80:4000
      - 443:4001
    volumes:
      - /etc/letsencrypt/live/teberl.de/privkey.pem:/usr/share/letsencrypt/privkey.pem
      - /etc/letsencrypt/live/teberl.de/fullchain.pem:/usr/share/letsencrypt/fullchain.pem
    env_file:
      - docker.env
    networks:
      - webnet